package net.apartium.cocoabeans.schematic.prop;

import org.jetbrains.annotations.ApiStatus;

import java.util.function.Function;

@ApiStatus.AvailableSince("0.0.46")
public interface BlockProp<T> {

    class Legacy {
        public static final String DATA = "LEGACY_DATA";
        public static final String SIGN_LINES = "LEGACY_SIGN_LINES";
    }

    String STAIRS_SHAPE = "STAIRS_SHAPE";
    String BAMBOO_LEAVES = "BAMBOO_LEAVES";
    String BED_PART = "BED_PART";
    String BEEHIVE_HONEY_LEVEL = "BEEHIVE_HONEY_LEVEL";
    String BELL_ATTACHMENT = "BELL_ATTACHMENT";
    String BIG_DRIP_LEAF_TILT = "BIG_DRIP_LEAF_TILT";
    String BREWING_STAND_BOTTLES = "BREWING_STAND_BOTTLES";
    String CAKE_BITES = "CAKE_BITES";
    String CAMPFIRE_SIGNAL_FIRE = "CAMPFIRE_SIGNAL_FIRE";
    String BUBBLE_COLUMN_DRAG = "BUBBLE_COLUMN_DRAG";
    String CANDLE_CANDLES = "CANDLE_CANDLES";
    String CAVE_VINES_PLANT_BERRIES =  "CAVE_VINES_PLANT_BERRIES";
    String CHEST_TYPE = "CHEST_TYPE";
    String COMMAND_BLOCK_CONDITIONAL =  "COMMAND_BLOCK_CONDITIONAL";
    String COMPARATOR_MODE = "COMPARATOR_MODE";
    String DAY_LIGHT_DETECTOR_INVERTED = "DAY_LIGHT_DETECTOR_INVERTED";
    String DISPENSER_TRIGGERED = "DISPENSER_TRIGGERED";
    String DOOR_HINGE = "DOOR_HINGE";
    String END_PORTAL_FRAME_EYE = "END_PORTAL_FRAME_EYE";
    String FARM_LAND_MOISTURE = "FARM_LAND_MOISTURE";
    String GATE_IN_WALL = "GATE_IN_WALL";
    String HOPPER_ENABLED = "HOPPER_ENABLED";
    String JIGSAW_ORIENTATION = "JIGSAW_ORIENTATION";
    String JUKEBOX_HAS_RECORD = "JUKEBOX_HAS_RECORD";
    String LEAVES_PERSISTENT = "LEAVES_PERSISTENT";
    String LEAVES_DISTANCE = "LEAVES_DISTANCE";
    String LECTERN_HAS_BOOK = "LECTERN_HAS_BOOK";
    String NOTE_BLOCK_INSTRUMENT = "NOTE_BLOCK_INSTRUMENT";
    String NOTE_BLOCK_NOTE = "NOTE_BLOCK_NOTE";
    String PISTON_EXTENDED = "PISTON_EXTENDED";
    String PISTON_HEAD_IS_SHORT = "PISTON_HEAD_IS_SHORT";
    String POINTED_DRIPSTONE_VERTICAL_DIRECTION = "POINTED_DRIPSTONE_VERTICAL_DIRECTION";
    String POINTED_DRIPSTONE_THICKNESS = "POINTED_DRIPSTONE_THICKNESS";
    String REDSTONE_WIRE_CONNECTIONS = "REDSTONE_WIRE_CONNECTIONS";
    String REPEATER_DELAY = "REPEATER_DELAY";
    String REPEATER_LOCKED = "REPEATER_LOCKED";
    String RESPAWN_ANCHOR_CHARGES = "RESPAWN_ANCHOR_CHARGES";
    String SAPLING_STAGE = "SAPLING_STAGE";
    String SCAFFOLDING_BOTTOM = "SCAFFOLDING_BOTTOM";
    String SCAFFOLDING_DISTANCE = "SCAFFOLDING_DISTANCE";
    String SCULK_CATALYST_BLOOM = "SCULK_CATALYST_BLOOM";
    String SCULK_SENSOR_PHASE = "SCULK_SENSOR_PHASE";
    String SCULK_SHRIEKER_CAN_SUMMON = "SCULK_SHRIEKER_CAN_SUMMON";
    String SCULK_SHRIEKER_SHRIEKING = "SCULK_SHRIEKER_SHRIEKING";
    String SEA_PICKLE_PICKLES = "SEA_PICKLE_PICKLES";
    String SLAB_TYPE = "SLAB_TYPE";
    String SNOW_LAYERS = "SNOW_LAYERS";
    String STRUCTURE_BLOCK_MODE = "STRUCTURE_BLOCK_MODE";
    String TECHNICAL_PISTON_TYPE = "TECHNICAL_PISTON_TYPE";
    String TNT_UNSTABLE = "TNT_UNSTABLE";
    String TRIPWIRE_DISARMED = "TRIPWIRE_DISARMED";
    String TURTLE_EGG_EGGS = "TURTLE_EGG_EGGS";
    String TURTLE_EGG_HATCH = "TURTLE_EGG_HATCH";
    String WALL_UP = "WALL_UP";
    String WALL_HEIGHTS =  "WALL_HEIGHTS";
    String AGEABLE_AGE = "AGEABLE_AGE";
    String ANALOGUE_POWERABLE_POWER = "ANALOGUE_POWERABLE_POWER";
    String ATTACHABLE_ATTACHED = "ATTACHABLE_ATTACHED";
    String BISECTED_HALF = "BISECTED_HALF";
    String DIRECTIONAL = "DIRECTIONAL";
    String FACE_ATTACHABLE_ATTACHED_FACE = "FACE_ATTACHABLE_ATTACHED_FACE";
    String HANGABLE_HANGING = "HANGABLE_HANGING";
    String LEVELLED_LEVEL = "LEVELLED_LEVEL";
    String LIGHTABLE_LIT = "LIGHTABLE_LIT";
    String MULTIPLE_FACING_FACES =  "MULTIPLE_FACING_FACES";
    String OPENABLE_OPEN = "OPENABLE_OPEN";
    String ORIENTABLE_AXIS = "ORIENTABLE_AXIS";
    String POWERABLE_POWERED = "POWERABLE_POWERED";
    String RAIL_SHAPE = "RAIL_SHAPE";
    String ROTATABLE_ROTATION = "ROTATABLE_ROTATION";
    String SNOWABLE_SNOWY = "SNOWABLE_SNOWY";
    String WATERLOGGED_IS =  "WATERLOGGED_IS";

    Function<String[], ArrayStringBlockProp> ARRAY_STRING = ArrayStringBlockProp::new;

    T value();

}
