run-name: Build project

on:
  workflow_call:
    secrets:
      SIGNING_SECRET:
        required: true
      SIGNING_PASSWORD:
        required: true
    inputs:
      VERSION:
        description: 'Version name'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run shadowJar
        run: ./gradlew shadowJar
        env:
          VERSION: ${{ inputs.VERSION }}
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: cocoa-beans
          path: plugin/build/libs/*jar