name: Github release

on:
  workflow_call:
    inputs:
      VERSION:
        description: 'Version name'
        required: true
        type: string

permissions:
  pull-requests: write
  contents: write
  repository-projects: write
  packages: write
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload
        uses: IdanKoblik/Changelog@prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ inputs.VERSION }}
          assets: '["./plugin/build/libs/*jar"]'