name: Pull request CI

on:
  pull_request

jobs:
  unit_test:
    uses: ./.github/workflows/callable.test.yml
    secrets: inherit

  writerside_test:
    uses: ./.github/workflows/callable.writerside.yml
      