name: Pull request CI

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run integration tests
        run: |
          ls -la
          ./gradlew test
          ls -la
      - name: Publish `build-logic` Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build-logic/build/test-results/intTest/TEST-*.xml'
      - name: Publish `commands` Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/commands/build/test-results/intTest/TEST-*.xml'
      - name: Publish `common` Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/common/build/test-results/intTest/TEST-*.xml'
      - name: Publish `plugin` Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/plugin/build/test-results/intTest/TEST-*.xml'
      - name: Publish `spigot` Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/spigot/build/test-results/intTest/TEST-*.xml'