name: Pull request CI

on:
  pull_request

jobs:
  unit_test:
    uses: PoweredByApartium/cocoa-beans/.github/workflows/callable.test.yml@release-ci

  writerside_test:
    uses: PoweredByApartium/cocoa-beans/.github/workflows/callable.writerside.yml@release-ci
      