name: Pull request CI

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - build-logic
          - commands
          - common
          - plugin
          - spigot

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run integration tests
        run: ./gradlew test

      - name: Publish Test Reports
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          name: ${{ matrix.module }}
          report_paths: '**/build/test-results/test/TEST-*.xml'