name: Pull request CI

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run integration tests
        run: ./gradlew test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          detailed_summary: true
          follow_symlink: true
          check_name: |
            commands
            common
            spigot
          report_paths: |
            **/commands/build/test-results/test/TEST-*.xml
            **/common/build/test-results/test/TEST-*.xml
            **/spigot/build/test-results/test/TEST-*.xml