name: Pull request CI

on:
  pull_request:
    branches:
      - main

jobs:
  unit_test:
    uses: ./.github/workflows/callable.test.yml

  writerside_test:
    uses: ./.github/workflows/callable.writerside.yml
      