name: Base setup

on:
  workflow_call:
    outputs:
      dir:
        description: 'The path to the created directory'

env:
  INSTANCE: 'Writerside/cb'
  ARTIFACT: 'webHelpHI2-all.zip'
  DOCKER_VERSION: '233.14938'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: '45-new-docs-r'
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Generate javadocs
        run: ./gradlew javadoc
      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}
      - name: Create pages directory
        id: docs
        run: |
          mkdir docs 
          mkdir docs/common
          mkdir docs/spigot
          mkdir docs/commands
          mkdir docs/commands-spigot
          unzip artifacts/webHelpCB2-all.zip -d docs
          ls docs/
          cp -a common/build/docs/javadoc/* docs/common
          cp -a spigot/build/docs/javadoc/* docs/spigot
          cp -a commands/build/docs/javadoc/* docs/commands
          cp -a commands/spigot-platform/build/docs/javadoc/* docs/commands-spigot
          echo "::set-output name=dir::$GITHUB_WORKSPACE/docs"