name: Build

on:
  push:
    branches:
      - 45-new-docs-r #TODO fix
    tags:
      - v0.0.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Generate javadocs
        run: ./gradlew javadoc
      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: 'Writerside/cb'
          artifact: 'webHelpHI2-all.zip'
          docker-version: '233.14938'
      - name: Create and populate docs directory
        run: |
          mkdir -p docs/{common,spigot,commands,commands-spigot}
          unzip artifacts/webHelpCB2-all.zip -d docs
          cp -a common/build/docs/javadoc/* docs/common
          cp -a spigot/build/docs/javadoc/* docs/spigot
          cp -a commands/build/docs/javadoc/* docs/commands
          cp -a commands/spigot-platform/build/docs/javadoc/* docs/commands-spigot
      - name: Upload docs artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs